### ISSUE TITLE
Error: Python interpreter version (3.6) is lower than PyO3's minimum supported version (3.7)

### ISSUE THREAD

**Issue by twiecki** [PyO3/maturin-action#129]
```
  error: the configured Python interpreter version (3.6) is lower than PyO3's minimum supported version (3.7)
warning: build failed, waiting for other jobs to finish...
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit status: 101": `"cargo" "rustc" "--release" "--target" "x86_64-unknown-linux-gnu" "--manifest-path" "/home/runner/work/nutpie/nutpie/Cargo.toml" "--message-format" "json" "--lib"`
Error: The process '/usr/bin/docker' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/PyO3/maturin-action/v1/dist/index.js:1702:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/PyO3/maturin-action/v1/dist/index.js:1685:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/PyO3/maturin-action/v1/dist/index.js:1579:27)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
Error: The process '/usr/bin/docker' failed with exit code 1
```

This is the PR: https://github.com/pymc-devs/nutpie/pull/29
I don't see Python 3.6 specified anywhere, just 3.9.

**Comment by messense** [comment]
The default `python3` in manylinux2014 x86_64 docker image is Python 3.6.

Don't copy abi3 example for a non-abi3 project, you can refer to https://github.com/messense/py-dissimilar/blob/main/.github/workflows/CI.yml instead.

**Comment by twiecki** [comment]
Thanks! And while I have you, don't I need to set a token somewhere?

**Comment by messense** [comment]
> don't I need to set a token somewhere?

The [PyPI upload token](https://pypi.org/help/#apitoken) needs to be set in secrets, see https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository

https://github.com/messense/py-dissimilar/blob/86bb5e95826d9818a02b4a9f67c3d41be5df3760/.github/workflows/CI.yml#L232, it's called `PYPI_PASSWORD` (Maybe it's better to be named as `PYPI_TOKEN`).

**Comment by pattonw** [comment]
The default action built with `maturin generate-ci github > .github/workflows/CI.yml` uses "--find-interpreter" instead of listing out the versions as in the example @messense linked: https://github.com/messense/py-dissimilar/blob/main/.github/workflows/CI.yml
This leads to the issue mentioned above for python3.6 on targets [aarch64, armv7, s390x, ppc64le].
Should the default maturin action not be compatible with the default pyo3 project? It seems to use python3.6 I need to use the abi3 feature and use `abi3-py36`
