### ISSUE TITLE
build failures error pulling image configuration

### ISSUE THREAD

**Issue by chris-pattern** [PyO3/maturin-action#163]
My maturin-action builds have started failing today.  I'm assuming this is related to Github updating their [RSA host key](https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/).  We haven't changed our github action in a couple weeks.

The error is:
```
  error pulling image configuration: download failed after attempts=6: x509: certificate is valid for *.githubassets.com, githubassets.com, not pkg-containers.githubusercontent.com
```

Github action rule:
```
  linux-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: PyO3/maturin-action@v1
        with:
          target: aarch64
          manylinux: auto
          args: -m piranha/piranha-python/Cargo.toml --release -o dist -i ${{ env.PYTHON_VERSION }}
          sccache: 'true'
```

Github action log:
```
Run PyO3/maturin-action@v1
  with:
    target: aarch64
    manylinux: auto
    args: -m piranha/piranha-python/Cargo.toml --release -o dist -i 3.10
    sccache: true
    token: ***
    command: build
  env:
    PYTHON_VERSION: 3.10
    pythonLocation: /opt/hostedtoolcache/Python/3.10.10/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.10/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.10/x64
    Python[2](https://github.com/pattern-research/pattern/actions/runs/4515338556/jobs/7952513911#step:4:2)_ROOT_DIR: /opt/hostedtoolcache/Python/[3](https://github.com/pattern-research/pattern/actions/runs/4515338556/jobs/7952513911#step:4:3).10.10/x6[4](https://github.com/pattern-research/pattern/actions/runs/4515338556/jobs/7952513911#step:4:4)
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.10/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.10/x64/lib
Found maturin version requirement maturin>=0.14,<0.1[5](https://github.com/pattern-research/pattern/actions/runs/4515338556/jobs/7952513911#step:4:5) specified in pyproject.toml
Found maturin release from manifest: v0.14.15
Pull Docker image
  Using ghcr.io/rust-cross/manylinux2014-cross:aarch[6](https://github.com/pattern-research/pattern/actions/runs/4515338556/jobs/7952513911#step:4:6)4 Docker image
  /usr/bin/docker pull ghcr.io/rust-cross/manylinux2014-cross:aarch64
  aarch64: Pulling from rust-cross/manylinux2014-cross
  6[7](https://github.com/pattern-research/pattern/actions/runs/4515338556/jobs/7952513911#step:4:7)7076032cca: Pulling fs layer
  6e0ee949c901: Pulling fs layer
  6cb3b1ffcd79: Pulling fs layer
  a4bb57320cee: Pulling fs layer
  eafb7a72c4[8](https://github.com/pattern-research/pattern/actions/runs/4515338556/jobs/7952513911#step:4:8)7: Pulling fs layer
  a4bb57320cee: Waiting
  eafb7a72c487: Waiting
  1a2dc4f82ba2: Pulling fs layer
  f[9](https://github.com/pattern-research/pattern/actions/runs/4515338556/jobs/7952513911#step:4:9)a3701c1c34: Pulling fs layer
  c4[12](https://github.com/pattern-research/pattern/actions/runs/4515338556/jobs/7952513911#step:4:12)[16](https://github.com/pattern-research/pattern/actions/runs/4515338556/jobs/7952513911#step:4:16)422bb8: Pulling fs layer
  ffbb0ca6579d: Pulling fs layer
  1a2dc4f82ba2: Waiting
  f9a3701c1c34: Waiting
  c41[21](https://github.com/pattern-research/pattern/actions/runs/4515338556/jobs/7952513911#step:4:22)64[22](https://github.com/pattern-research/pattern/actions/runs/4515338556/jobs/7952513911#step:4:23)bb8: Waiting
  ffbb0ca6579d: Waiting
  6cb3b1ffcd79: Downloading
  6cb3b1ffcd79: Retrying in 5 seconds
  6770760[32](https://github.com/pattern-research/pattern/actions/runs/4515338556/jobs/7952513911#step:4:33)cca: Retrying in 5 seconds
  6e0ee949c901: Retrying in 5 seconds
  6cb3b1ffcd79: Retrying in 4 seconds
  677076032cca: Retrying in 4 seconds
  6e0ee949c901: Retrying in 4 seconds
  6cb3b1ffcd79: Retrying in 3 seconds
  677076032cca: Retrying in 3 seconds
  6e0ee949c901: Retrying in 3 seconds
  6cb3b1ffcd79: Retrying in 2 seconds
  677076032cca: Retrying in 2 seconds
  6e0ee9[49](https://github.com/pattern-research/pattern/actions/runs/4515338556/jobs/7952513911#step:4:50)c901: Retrying in 2 seconds
  6cb3b1ffcd79: Retrying in 1 second
  677076032cca: Retrying in 1 second
  6e0ee949c901: Retrying in 1 second
  error pulling image configuration: download failed after attempts=6: x509: certificate is valid for *.githubassets.com, githubassets.com, not pkg-containers.githubusercontent.com
Error: The process '/usr/bin/docker' failed with exit code 1
      at ExecState._setResult (/home/runner/work/_actions/PyO3/maturin-action/v1/dist/index.js:1702:25)
      at ExecState.CheckComplete (/home/runner/work/_actions/PyO3/maturin-action/v1/dist/index.js:1685:18)
      at ChildProcess.<anonymous> (/home/runner/work/_actions/PyO3/maturin-action/v1/dist/index.js:1[57](https://github.com/pattern-research/pattern/actions/runs/4515338556/jobs/7952513911#step:4:58)9:27)
      at ChildProcess.emit (node:events:527:28)
      at maybeClose (node:internal/child_process:1092:16)
      at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
  Error: The process '/usr/bin/docker' failed with exit code 1
```

**Comment by messense** [comment]
> x509: certificate is valid for *.githubassets.com, githubassets.com, not pkg-containers.githubusercontent.com

Looks like a configuration issue with SSL certificate, if the issue persists please contact GitHub support. Nothing we can we here.

**Comment by chris-pattern** [comment]
Thanks for link
