### ISSUE TITLE
Does this action work with nektos/act?

### ISSUE THREAD

**Issue by Swandog** [PyO3/maturin-action#207]
I'm trying to use https://github.com/nektos/act to run a workflow that has maturin-action in it...but the action fails:

```
[Python: Build and Test/linux      ] ⭐ Run Main Build wheels
[Python: Build and Test/linux      ]   🐳  docker cp src=/Users/swandog/.cache/act/PyO3-maturin-action@v1/ dst=/var/run/act/actions/PyO3-maturin-action@v1/
[Python: Build and Test/linux      ]   🐳  docker exec cmd=[node /var/run/act/actions/PyO3-maturin-action@v1/dist/index.js] user= workdir=
| Found maturin version requirement maturin>=0.13,<0.14 specified in pyproject.toml
[Python: Build and Test/linux      ]   💬  ::debug::maturin version spec: >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 1.2.3 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 1.2.2 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 1.2.1 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 1.2.0 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 1.1.0 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 1.0.1 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 1.0.0 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 0.15.3 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 0.15.2 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 0.15.1 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 0.15.0 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 1.0.0-beta.9 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 1.0.0-beta.8 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 0.14.17 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 1.0.0-beta.7 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 0.14.16 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 1.0.0-beta.5 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 0.14.15 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 1.0.0-beta.4 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 0.14.14 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 1.0.0-beta.2 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 1.0.0-beta.1 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 0.14.13 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 0.14.12 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 0.14.11 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 0.14.10 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 0.14.9 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 0.14.8 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 0.14.8-beta.2 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 0.14.8-beta.1 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 0.14.7 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 0.14.7-beta.1 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 0.14.6 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 0.14.5 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 0.14.4 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 0.14.3 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 0.14.2 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 0.14.1 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 0.14.0 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 0.14.0-beta.7 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 0.14.0-beta.6 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 0.14.0-beta.5 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 0.14.0-beta.4 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 0.14.0-beta.3 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::check 0.13.7 satisfies >=0.13 <0.14
[Python: Build and Test/linux      ]   💬  ::debug::x64===x64 && darwin===linux
[Python: Build and Test/linux      ]   💬  ::debug::x64===x64 && linux===linux
[Python: Build and Test/linux      ]   💬  ::debug::matched 0.13.7
| Found maturin release from manifest: v0.13.7
| Using existing quay.io/pypa/manylinux2014_x86_64:latest Docker image
| Error: Unable to locate executable file: cargo. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
|     at Object.<anonymous> (/run/act/actions/PyO3-maturin-action@v1/dist/index.js:4088:27)
|     at Generator.next (<anonymous>)
|     at fulfilled (/run/act/actions/PyO3-maturin-action@v1/dist/index.js:3899:58)
[Python: Build and Test/linux      ]   ❗  ::error::Unable to locate executable file: cargo. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
[Python: Build and Test/linux      ]   ❌  Failure - Main Build wheels
[Python: Build and Test/linux      ]   ⚙  ::set-env:: CARGO_INCREMENTAL=0
[Python: Build and Test/linux      ]   ⚙  ::set-env:: CARGO_TERM_COLOR=always
[Python: Build and Test/linux      ] exitcode '1': failure
[Python: Build and Test/linux      ] 🏁  Job failed
```

This workflow works on GitHub. Do I need to do some setup to prepare the local machine for maturin-action?

**Comment by messense** [comment]
No idea. This action assumes running in GitHub runners, so if `act` environment isn't the same it may fail. In your case you are missing `cargo`/`rust` in `act` environment.

**Comment by dbarnett** [comment]
FWIW I just ran into the same (different executable `python3`, but same error and looks like same cause).

I'm not super familiar with what layers of image/platform setup gh-act performs and how those would be different from the genuine GH Actions equivalents, to account for any discrepancies in the env and $PATH. Anyone have a pointer to details?
