### ISSUE TITLE
Executing sdist command fails because of too many downloaded Rust targets

### ISSUE THREAD

**Issue by pemistahl** [PyO3/maturin-action#208]
I use the generated CI yaml file for the workflow of one of my Rust projects. When trying to execute the sdist command within the workflow on Ubuntu, the workflow fails after 18 minutes with the following exception:

```
System.IO.IOException: No space left on device : '/home/runner/runners/2.308.0/_diag/Worker_20230827-182408-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
System.IO.IOException: No space left on device : '/home/runner/runners/2.308.0/_diag/Worker_20230827-182408-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Common.Tracing.Error(Exception exception)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
Unhandled exception. System.IO.IOException: No space left on device : '/home/runner/runners/2.308.0/_diag/Worker_20230827-182408-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at System.Diagnostics.TraceSource.Flush()
   at GitHub.Runner.Common.TraceManager.Dispose(Boolean disposing)
   at GitHub.Runner.Common.TraceManager.Dispose()
   at GitHub.Runner.Common.HostContext.Dispose(Boolean disposing)
   at GitHub.Runner.Common.HostContext.Dispose()
   at GitHub.Runner.Worker.Program.Main(String[] args)
```

Unfortunately, the cause of the problem is not visible in the action run screen. After switching from Ubuntu to macOS for executing the sdist command, the action run shows that it tries to download and compile lots and lots of Rust targets which are not needed at all when just the sources are supposed to be zipped. After more than 50 (!) minutes, I canceled the workflow:

```
...
Downloaded windows_aarch64_gnullvm v0.48.0
Downloaded rustix v0.38.4
Downloaded windows_x86_64_gnullvm v0.48.0
Downloaded serde_derive v1.0.174
Downloaded pyo3 v0.19.2
Downloaded windows_aarch64_msvc v0.48.0
Downloaded windows_x86_64_msvc v0.48.0
Downloaded web-sys v0.3.64
Downloaded windows_i686_gnu v0.48.0
Downloaded windows_x86_64_gnu v0.48.0
Downloaded windows_i686_msvc v0.48.0
Downloaded winapi v0.3.9
Downloaded windows-sys v0.48.0
Downloaded winapi-x86_64-pc-windows-gnu v0.4.0
Downloaded winapi-i686-pc-windows-gnu v0.4.0
...
```

Can you please fix that by not downloading any Rust targets for the sdist command? Otherwise, this command will take ages and completely fill the disk space of the virtual machines.

Action run on Ubuntu: https://github.com/pemistahl/grex/actions/runs/5992538831
Action run on macOS: https://github.com/pemistahl/grex/actions/runs/5992648093

**Comment by messense** [comment]
> Can you please fix that by not downloading any Rust targets for the sdist command?

Sorry I don't think we can do that because that's done by `cargo metadata` / `cargo package` command which sdist command uses internally.

Also I don't think just download some Rust crates would fill up disk space, it's really not that big. I think the problem might be the generated sdist `.tar.gz` is been added to sdist again and again because it's not ignored by `.gitignore`.

**Comment by pemistahl** [comment]
> Sorry I don't think we can do that because that's done by `cargo metadata` / `cargo package` command which sdist command uses internally.

When I execute `maturin sdist` on my local machine, it does not do anything like that. It simply puts all sources without the `target` folder in a `.tar.gz` file which takes only a few milliseconds to complete. I don't understand what is going on in your GitHub action.

> I think the problem might be the generated sdist `.tar.gz` is been added to sdist again and again because it's not ignored by `.gitignore`.

Why is the archive added to the sdist command again? Is the command executed multiple times with content being added recursively to it? This sounds like nonsense to me. The sdist command should only be executed exactly once and put the source files and nothing else into the archive.

Can you please elaborate on how this GitHub action exactly works? It's obviously badly documented and I don't understand it. Thank you.

**Comment by messense** [comment]
> I don't understand what is going on in your GitHub action.

https://github.com/pemistahl/grex/blob/0f9c2d9012d0900f6a05a57c2df6485631186581/.github/workflows/python-release.yml#L37

**Comment by messense** [comment]
For sdist, this actions simply invoke `maturin sdist` with passed in `args`, in your case the full command is `maturin sdist --out dist`.

**Comment by pemistahl** [comment]
And why is the sdist command apparently executed multiple times instead of just once?

**Comment by messense** [comment]
No, it's only executed once, it's just some other code path in `maturin` included the not-`gitignored` sdist output file, probably `cargo package --list` somehow. There was a check added in https://github.com/PyO3/maturin/pull/575 which doesn't seem to work in this case. 

Hey it's an open source project, you are welcome to investigate if you want to solve the issue instead of simply workaround it by adding `dist/` to `.gitignore`.

**Comment by pemistahl** [comment]
Alright, thank you for the explanation @messense. I just wanted to understand what's going on. If I find the time (but probably won't) I will gladly try to improve the code and/or the documentation.
