### ISSUE TITLE
Failed to build a native library through cargo (aarch64-unknown-linux-gnu)

### ISSUE THREAD

**Issue by orhun** [PyO3/maturin-action#245]
Hello! I have a GitHub Action where I build wheels for PyPI using `PyO3/maturin-action`.

I have a build matrix and the build step only fails for `aarch64-unknown-linux-gnu` with the following error:

```
warning: build failed, waiting for other jobs to finish...
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit status: 101": `"cargo" "rustc" "--release" "--target" "aarch64-unknown-linux-gnu" "--manifest-path" "/home/runner/work/git-cliff/git-cliff/git-cliff/Cargo.toml" "--message-format" "json" "--bin" "git-cliff-completions"`
Error: The process '/usr/bin/docker' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/PyO3/maturin-action/v1/dist/index.js:1702:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/PyO3/maturin-action/v1/dist/index.js:1685:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/PyO3/maturin-action/v1/dist/index.js:1579:27)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

Also there are errors such as:

```
warning: ring@0.17.7: In file included from /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.17.7/pregenerated/aesv8-armx-linux64.S:4:0:
warning: ring@0.17.7: include/ring-core/asm_base.h:73:2: error: #error "ARM assembler must define __ARM_ARCH"
warning: ring@0.17.7:  #error "ARM assembler must define __ARM_ARCH"
```

I attached the full logs.

[maturin-aarch64-unknown-linux-gnu.log](https://github.com/PyO3/maturin/files/14322654/maturin-aarch64-unknown-linux-gnu.log)

Here you can check them out as well: https://github.com/orhun/git-cliff/actions/runs/7948456535/job/21698502551

Let me know if I should report this to `PyO3/maturin` as well.

**Comment by messense** [comment]
See #222
