### ISSUE TITLE
Attempting to include the sdist output tarball [...] into itself

### ISSUE THREAD

**Issue by sk1p** [PyO3/maturin-action#99]
For one of my packages, the Linux build fails with the following message:

```
Run messense/maturin-action@v1
Found maturin version requirement maturin>=0.13,<0.14 specified in pyproject.toml
Found maturin release from manifest: v0.13.7
Found Rust toolchain stable in rust-toolchain.toml 
Pull Docker image
Cleanup build scripts artifact directory
/usr/bin/docker run --rm --workdir /home/runner/work/LiberTEM-dectris-rs/LiberTEM-dectris-rs -e DEBIAN_FRONTEND=noninteractive -e ARCHFLAGS -e _PYTHON_SYSCONFIGDATA_NAME -v /home/runner/work/LiberTEM-dectris-rs/LiberTEM-dectris-rs:/home/runner/work/LiberTEM-dectris-rs/LiberTEM-dectris-rs ghcr.io/libertem/manylinux2014_x[8](https://github.com/LiberTEM/LiberTEM-dectris-rs/actions/runs/3429314498/jobs/5714765736#step:3:9)6_64:latest /home/runner/work/LiberTEM-dectris-rs/LiberTEM-dectris-rs/run-maturin-action.sh
Install Rust
Install maturin
🔗 Found pyo3 bindings with abi3 support for Python ≥ 3.7
🐍 Not using a specific python interpreter
💥 maturin failed
  Caused by: Failed to build source distribution
  Caused by: Attempting to include the sdist output tarball dist/libertem_dectris-0.2.2.tar.gz into itself! Check 'cargo package --list' output.
Error: The process '/usr/bin/docker' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/messense/maturin-action/v1/dist/index.js:1702:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/messense/maturin-action/v1/dist/index.js:1685:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/messense/maturin-action/v1/dist/index.js:157[9](https://github.com/LiberTEM/LiberTEM-dectris-rs/actions/runs/3429314498/jobs/5714765736#step:3:10):27)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:[10](https://github.com/LiberTEM/LiberTEM-dectris-rs/actions/runs/3429314498/jobs/5714765736#step:3:11)64:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
Error: The process '/usr/bin/docker' failed with exit code 1
```

Full log available here: https://github.com/LiberTEM/LiberTEM-dectris-rs/actions/runs/3429314498/jobs/5714765736

Previous builds (without configuration changes beyond now using a new maturin version), and the corresponding Mac OS / Windows builds, complete successfully. Manually building on Linux doesn't reproduce the issue, so it could be a problem in this action or how we are using it. Thanks!

**Comment by messense** [comment]
It should have be filtered out by `.gitignore`, but somehow it didn't. I think I can change it to just ignore the sdist file.

**Comment by messense** [comment]
In the meantime, you can try to change output directory to `target/dist`: `-o target/dist`

**Comment by uellue** [comment]
> In the meantime, you can try to change output directory to `target/dist`: `-o target/dist`

Thank you, that seems to have fixed it for now!
